version: '3.9'

services:
  backend:
    container_name: backend-demo
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    build:
      context: .
      dockerfile: .Dockerfile
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python manage.py runserver"
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - demo-net

networks:
  demo-net: